config/routes.rb
Rails.application.routes.draw do
	resources :articles, :issue_links
	post '/articles/:id' => 'articles#feature', :as => :feature_article
	resources :drafts, only: [:edit, :update, :destroy, :index]
	devise_for :editors, :skip => [:registrations]
	as :editor do
	  get 'editors/edit' => 'devise/registrations#edit', :as => 'edit_editor_registration'
	  put 'editors' => 'devise/registrations#update', :as => 'editor_registration'
	  delete 'editors' => 'devise/registrations#destroy', :as => 'destroy_editor_registration'
	end
	devise_for :admins, :skip => [:registrations]
	as :admin do
	  get 'admins/edit' => 'devise/registrations#edit', :as => 'edit_admin_registration'
	  put 'admins' => 'devise/registrations#update', :as => 'admin_registration'
	end
	match 'admin/:id' => 'admins#destroy', :via => :delete, :as => :admin_destroy_editor
	get '/admin' => 'admins#home'
	get '/admin/manage' => 'admins#manage'
	put '/admin/manage/:id' => 'admins#verify', :method => :put, :as => :verify_editor
	get '/editor' => 'editors#home'
	root 'articles#index'
	get '/search' => 'search#search'
	get '/contacts' => 'contacts#new'
	resources "contacts", only: [:new, :create]
	get '/about' => 'home#about'
end

app/views/admins/home.html.erb
<h1>Admin logged in</h1>
<%= link_to 'Edit Profile', edit_admin_registration_path %>
<br><br>
<%= link_to 'Manage Admins', admin_manage_path %>

app/views/admins/manage.html.erb
<div class="container">
    <div class="row">
        <div class="col-lg-8 col-md-8">
            <h2>Manage Editors</h2>
            <% unless @editors.count == 0 %>
                <% @editors.each do |editor| %>
                    <% unless current_editor == editor %>
                        <div>
                            <h3><%= editor.email %></h3>
                            <%= link_to "Delete", admin_destroy_editor_path(editor), method: :delete, data: { confirm: "Are you sure you want to delete #{editor.email}?" } %>
                        </div>
                    <% end %>
                <% end %>
            <% else %>
                <h3>There are no editors</h3>
            <% end %>
        </div>
    </div>

    <br>

    <%= link_to "Invite Editor", new_editor_invitation_path %>
</div>