config/routes.rb
Rails.application.routes.draw do
	resources :articles, :issue_links
	post '/articles/:id' => 'articles#feature', :as => :feature_article
	resources :drafts, only: [:edit, :update, :destroy, :index]
	devise_for :editors, :skip => [:registrations]
	as :editor do
	  get 'editors/edit' => 'devise/registrations#edit', :as => 'edit_editor_registration'
	  put 'editors' => 'devise/registrations#update', :as => 'editor_registration'
	  delete 'editors' => 'devise/registrations#destroy', :as => 'destroy_editor_registration'
	end
	devise_for :admins, :skip => [:registrations]
	as :admin do
	  get 'admins/edit' => 'devise/registrations#edit', :as => 'edit_admin_registration'
	  put 'admins' => 'devise/registrations#update', :as => 'admin_registration'
	end
	match 'admin/:id' => 'admins#destroy', :via => :delete, :as => :admin_destroy_editor
	get '/admin' => 'admins#home'
	get '/admin/manage' => 'admins#manage'
	put '/admin/manage/:id' => 'admins#verify', :method => :put, :as => :verify_editor
	get '/editor' => 'editors#home'
	root 'articles#index'
	get '/search' => 'search#search'
	get '/contacts' => 'contacts#new'
	resources "contacts", only: [:new, :create]
	get '/about' => 'home#about'
end

app/models/article.rb
class Article < ActiveRecord::Base
	is_impressionable
	validate :title_or_photo
	has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: ""
  	validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/

	def self.search(search)
  		where("LOWER(title) LIKE LOWER(?) OR LOWER(content) LIKE LOWER(?)", "%#{search}%", "%#{search}%")
	end

	private
		def title_or_photo
		  	if title.blank? && photo.blank?
		    	errors[:base] << "An article must have at least a photo or a title"
		  	end
		end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :authenticate_editor!, except: [:show, :index]
	impressionist :actions=>[:show]

	def index
		@articles = Article.all.where(featured: 0).order('created_at desc').limit(13)
		@featured_1 = Article.where(featured: 1).take
		@featured_2 = Article.where(featured: 2).take
		@featured_3 = Article.where(featured: 3).take
		@latest_issue = IssueLink.order('date desc').take
	end

	def show
    	@article = Article.find(params['id'])
		@latest_articles = Article.all.where(featured: 0).where.not(id: @article).order('created_at desc').limit(5)
		@featured_articles = Article.where.not(featured: 0, id: @article)
		@article_views = @article.impressionist_count(:filter=>:session_hash)
	end

	def new
		@article = Article.new
	end

	def create
		if params[:commit] == 'Publish'
			@article = Article.new(article_params)

			if @article.save
			  redirect_to @article
			else
				render 'new'
			end
		elsif params[:commit] == 'Save Draft'
			@draft = Draft.new(article_params)

			if @draft.save
			  redirect_to edit_draft_path(@draft)
			else
				render 'new'
			end
		end
	end

	def edit
		@article = Article.find(params[:id])
	end

	def update
		if params[:commit] == 'Publish'
			@article = Article.find(params[:id])

			if @article.update(article_params)
				redirect_to @article
			else
				render 'edit'
			end
		elsif params[:commit] == 'Delete Photo'
			@article = Article.find(params[:id])
			@article.photo.destroy
			@article.save

			redirect_to edit_article_path
		end
	end

	def destroy
		@article = Article.find(params[:id])
		@article.destroy

		redirect_to articles_path
	end

	def feature
		@article = Article.find(params[:id])
		@old_feature = Article.where(featured: params["/articles/#{params[:id]}"][:feature]).take

		if @article.featured != 0 && !@old_feature.blank?
			@old_feature.featured = @article.featured
			@old_feature.save
		elsif !@old_feature.blank?
			@old_feature.featured = 0
			@old_feature.save
		end

		@article.featured = params["/articles/#{params[:id]}"][:feature]
		@article.save

		redirect_to root_path
	end



	private
		def article_params
			params.require(:article).permit(:title, :content, :photo, :author_name)
		end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= bootstrap_form_for @article, html: { multipart: true } do |f| %>
	<% if @article.errors.any? %>
		<div class="row">
			<div class="col-lg-2 col-md-2"></div>
			<div class="col-sm-12 col-md-9 col-lg-9">
				<div class="error_explanation">
					<h2>
						<%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:
					</h2>
					<ul>
						<% @article.errors.full_messages.each do |msg| %>
							<li><%= msg %></li>
						<% end %>
					</ul>
				</div>
			</div>
		</div>
	<% end %>

	<% unless @article.photo.url.blank? %>
		<div class="row">
			<div class="col-lg-2 col-md-2"></div>
			<div class="col-sm-12 col-md-9 col-lg-9">
				<p>
					<%= image_tag(@article.photo.url) %>
					<% if current_page?(action: 'edit', controller: 'articles') %>
						<%= f.submit "Delete Photo", class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this photo?' } %>
					<% end %>
				</p>
			</div>
		</div>
	<% end %>
	<div class="row">
		<div class="col-lg-2 col-md-2"></div>
		<div class="col-sm-12 col-md-9 col-lg-9">
			<p>
				<%= f.text_field :title, placeholder: 'Title...', autofocus: 'true', hide_label: true %>
			</p>
		</div>
	</div>

	<div class="row">
		<div class="col-lg-2 col-md-2"></div>
		<div class="col-sm-12 col-md-9 col-lg-9">
			<p>
				<%= f.text_area :content, placeholder: 'Article content...', rows: '15', hide_label: true %>
			</p>
		</div>
	</div>

	<div class="row">
		<div class="col-lg-2 col-md-2"></div>
		<div class="col-sm-12 col-md-9 col-lg-9">
		    <p>
		        <%= f.text_field :author_name, placeholder: 'Author name (optional)', hide_label: true %>
		    </p>
		</div>
	</div>

	<div class="row">
		<div class="col-lg-2 col-md-2"></div>
		<div class="col-sm-12 col-md-9 col-lg-9">
			<%= f.label(:photo, 'Add Photo') %><br>
			<div class="article-photo-input">
				<div class="wrapper">
					<%= f.file_field :photo, hide_label: true %>
				</div>
				<span class="glyphicon glyphicon-camera camera-icon"></span>
			</div>
		</div>
	</div>

	<div class="row">
		<div class="col-lg-2 col-md-2"></div>
		<div class="col-sm-12 col-md-9 col-lg-9">
			<p>
				<br>
				<% if current_page?(action: 'new', controller: 'articles') %>
					<%= f.submit "Save Draft", class: 'btn btn-primary' %>
				<% end %>
				<%= f.submit "Publish", class: 'btn btn-success', data: { confirm: 'Are you sure you want to publish?' } %>
			</p>
		</div>
	</div>

<% end %>

app/views/articles/edit.html.erb
<div class="edit-article">
	<div class="container">
		<div class="row">
			<div class="col-md-2 col-lg-2"></div>
			<div class="col-sm-12 col-lg-9 col-md-9">
				<h1>New Article</h1>
			</div>
		</div>
		<div class="edit-article-form">
			<%= render 'form' %>
		</div>
	</div>
</div>

app/views/articles/index.html.erb
<div class="container page-body-container">

	<div class="row features">
		<div class="col-md-3 col-lg-3 col-xs-12">
			<div class="latest-issue">
				<% unless @latest_issue.blank? %>
					<h4>Latest Issue</h4>
					<%= link_to issue_link_path(@latest_issue) do %>
						<div class="latest-issue-link">
							<div class="link-image">
				                <%= image_tag(@latest_issue.thumbnail_link) %>
				            </div>
							<h4 class="latest-issue-title"><%= @latest_issue.title %></h4>
						</div>
					<% end %>
				<% else %>
					No latest issue
				<% end %>
			</div>
		</div>
		<div class="col-md-5 col-lg-5 col-xs-12">
			<% unless @featured_1.blank? %>
				<%= link_to article_path(@featured_1.id) do %>
					<div class="featured-1">
						<div class="headline-img">
							<% unless @featured_1.photo.url.blank? %>
								<%= image_tag @featured_1.photo.url %>
							<% end %>
						</div>
						<% unless @featured_1.title.blank? %>
							<h3 class="headline-title"><%= @featured_1.title %></h3>
						<% end %>
						<% unless @featured_1.content.blank? %>
							<p class="headline-text"><%= @featured_1.content.first(200) %>...</p>
						<% end %>
					</div>
				<% end %>
			<% end %>
		</div>
		<div class="col-md-4 col-lg-4 visible-md visible-lg secondary-features">
			<% unless @featured_2.blank? %>
				<%= link_to article_path(@featured_2.id) do %>
					<div class="featured-2">
						<h3 class="featured-2-title"><%= @featured_2.title %></h3>
						<p class="featured-2-text"><%= @featured_2.content.first(200) %>...</p>
					</div>
				<% end %>
			<% end %>
			<% unless @featured_3.blank? %>
				<%= link_to article_path(@featured_3.id) do %>
					<div class="featured-3">
						<h3 class="featured-3-title"><%= @featured_3.title %></h3>
						<p class="featured-3-text"><%= @featured_3.content.first(200) %>...</p>
					</div>
				<% end %>
			<% end %>
		</div>
	</div>

	<div class="row">
		<div class="col-md-offset-1 col-lg-offset-1 col-md-8 col-lg-8">
			<ul class="article-list">
				<% unless @featured_2.blank? %>
					<%= link_to article_path(@featured_2), :class => "visible-xs" do %>
						<li class="article-in-list">
							<% unless @featured_2.photo.url.blank? %>
								<div class="article-list-photo">
									<%= image_tag(@featured_2.photo.url) %>
								</div>
							<% end %>
							<div class="article-list-title">
								<%= @featured_2.title %>
							</div>
						</li>
					<% end %>
				<% end %>
				<% unless @featured_3.blank? %>
					<%= link_to article_path(@featured_3), :class => "visible-xs" do %>
						<li class="article-in-list">
							<% unless @featured_3.photo.url.blank? %>
								<div class="article-list-photo">
									<%= image_tag(@featured_3.photo.url) %>
								</div>
							<% end %>
							<span class="article-list-title">
								<%= @featured_3.title %>
							</span>
						</li>
					<% end %>
				<% end %>
				<% unless @articles.empty? || !@articles %>
					<% @articles.each do |article| %>
						<%= link_to article_path(article) do %>
							<li class="article-in-list">
								<% unless article.photo.url.blank? %>
									<div class="article-list-photo">
										<%= image_tag(article.photo.url) %>
									</div>
								<% end %>
								<span class="article-list-title">
									<%= article.title %>
								</span>
							</li>
						<% end %>
					<% end %>
				<% else %>
					<h3>No articles</h3>
				<% end %>
			</ul>
		</div>
	</div>

</div>

app/views/articles/new.html.erb
<div class="new-article">
	<div class="container">
		<div class="row">
			<div class="col-md-2 col-lg-2"></div>
			<div class="col-sm-12 col-lg-9 col-md-9">
				<h1>New Article</h1>
			</div>
		</div>
		<div class="new-article-form">
			<%= render 'form' %>
		</div>
	</div>
</div>

app/views/articles/show.html.erb
<div class="container">
	<% if editor_signed_in? %>
		<div class="row">
			<div class="col-md-3 col-lg-3"></div>
			<div class="col-md-8 col-lg-8 article-edit-buttons">
				<%= bootstrap_form_for(feature_article_path(@article), layout: :inline) do |f| %>
					<%= f.select :feature, [['Headline', 1],['Subheadline 1', 2],['Subheadline 2', 3]] %>
					<%= f.submit :Submit %>
				<% end %>
				<%= button_to("Delete", { action: 'destroy', id: @article.id },
												method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger delete-button') %>
				<%= button_to("Edit", { action: 'edit', id: @article.id }, method: :get, class: 'btn btn-primary edit-button') %>
			</div>
			<div class="col-md-1 col-lg-1"></div>
		</div>
	<% end %>

	<div class="row">
		<div class="col-md-12 col-lg-12">
			<h1 class="article-title"><%= @article.title %></h1>
		</div>
	</div>

	<div class="row">
		<div class="col-md-2 col-lg-2 article-meta-data">
			<% unless @article.author_name.nil? %>
				<h3><%= @article.author_name %></h3>
			<% end %>
			<p><%= @article.created_at.strftime("%d/%m/%Y") %></p>
		</div>

		<div class="col-md-10 col-lg-10">
			<div class="row">
				<% unless @article.photo.url.blank? %>
					<div class="col-md-8 col-lg-8 article-photo">
						<%= image_tag @article.photo.url %>
					</div>
					<% unless @latest_articles.blank? %>
						<div class="col-md-3 col-lg-3 latest-articles visible-md visible-lg">
							<h4>Latest Articles</h4>
							<ul>
								<% @latest_articles.each do |article| %>
									<%= link_to article_path(article) do %>
										<li>
											<% unless article.photo.url.blank? %>
												<%= image_tag article.photo.url %>
											<% end %>
											<div>
												<%= article.title %>
											</div>
										</li>
									<% end %>
								<% end %>
							</ul>
						</div>
					<% end %>
				<% end %>
			</div>
			<div class="row">
				<div class="col-md-8 col-lg-8 col-xs-12 article-content">
		    		<%= simple_format(@article.content) %>
					<%= social_share_button_tag(@article.title, :image => !@article.photo.url.blank? ? @article.photo.url : '') %>
					<% if editor_signed_in? %>
						<div class="page-views">Page Views: <%= @article_views %></div>
					<% end %>
				</div>
				<% if @article.photo.url.blank? %>
					<% unless @latest_articles.blank? %>
						<div class="col-md-3 col-lg-3 latest-articles visible-md visible-lg">
							<h4>Latest Articles</h4>
							<ul>
								<% @latest_articles.each do |article| %>
									<%= link_to article_path(article) do %>
										<li>
											<% unless article.photo.url.blank? %>
												<%= image_tag article.photo.url %>
											<% end %>
											<div>
												<%= article.title %>
											</div>
										</li>
									<% end %>
								<% end %>
							</ul>
						</div>
					<% end %>
				<% end %>
			</div>

			<% unless @featured_articles.blank? %>
				<div class="row featured-articles visible-md visible-lg">
					<div class="col-lg-9 col-md-9">
						<h4>Featured Articles</h4>
						<ul>
							<% @featured_articles.each do |feature| %>
								<%= link_to article_path(feature) do %>
									<li>
										<% unless feature.photo.url.blank? %>
											<%= image_tag feature.photo.url %>
										<% end %>
										<div>
											<%= feature.title %>
										</div>
									</li>
								<% end %>
							<% end %>
						</ul>
					</div>
				</div>
			<% end %>
		</div>
	</div>
	<% unless @featured_articles.blank? %>
		<div class="row featured-articles visible-xs">
			<div class="col-xs-12">
				<h4>Featured Articles</h4>
				<ul>
					<% @featured_articles.each do |feature| %>
						<%= link_to article_path(feature) do %>
							<li>
								<% unless feature.photo.url.blank? %>
									<%= image_tag feature.photo.url %>
								<% end %>
								<div>
									<%= feature.title %>
								</div>
							</li>
						<% end %>
					<% end %>
				</ul>
			</div>
		</div>
	<% end %>
</div>