config/routes.rb
Rails.application.routes.draw do
	resources :articles, :issue_links
	post '/articles/:id' => 'articles#feature', :as => :feature_article
	resources :drafts, only: [:edit, :update, :destroy, :index]
	devise_for :editors, :skip => [:registrations]
	as :editor do
	  get 'editors/edit' => 'devise/registrations#edit', :as => 'edit_editor_registration'
	  put 'editors' => 'devise/registrations#update', :as => 'editor_registration'
	  delete 'editors' => 'devise/registrations#destroy', :as => 'destroy_editor_registration'
	end
	devise_for :admins, :skip => [:registrations]
	as :admin do
	  get 'admins/edit' => 'devise/registrations#edit', :as => 'edit_admin_registration'
	  put 'admins' => 'devise/registrations#update', :as => 'admin_registration'
	end
	match 'admin/:id' => 'admins#destroy', :via => :delete, :as => :admin_destroy_editor
	get '/admin' => 'admins#home'
	get '/admin/manage' => 'admins#manage'
	put '/admin/manage/:id' => 'admins#verify', :method => :put, :as => :verify_editor
	get '/editor' => 'editors#home'
	root 'articles#index'
	get '/search' => 'search#search'
	get '/contacts' => 'contacts#new'
	resources "contacts", only: [:new, :create]
	get '/about' => 'home#about'
end

app/models/editor.rb
class Editor < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable, :timeoutable, :confirmable, :invitable

  attr_readonly :email
  validates_format_of :email, with: /\@tcd\.ie/, message: 'You should have an email from tcd.ie'
end

app/controllers/editors_controller.rb
class EditorsController < ApplicationController
	before_action :authenticate_editor!

    def home
    end
end

app/helpers/editors_helper.rb
module EditorsHelper
end

app/views/editors/home.html.erb
<div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12">
        <div class="alert alert-info">
            Editor logged in
        </div>

        <ul class="list-group">
            <li class="list-group-item">
                <%= link_to 'New Article', new_article_path %>
            </li>
            <li class="list-group-item">
                <%= link_to 'Drafts', drafts_path %>
            </li>
            <li class="list-group-item">
                <%= link_to 'New Archive Link', new_issue_link_path %>
            </li>
            <li class="list-group-item">
                <%= link_to 'Edit Profile', edit_editor_registration_path %>
            </li>
        </ul>

    </div>
</div>