config/routes.rb
Rails.application.routes.draw do
	resources :articles, :issue_links
	post '/articles/:id' => 'articles#feature', :as => :feature_article
	resources :drafts, only: [:edit, :update, :destroy, :index]
	devise_for :editors, :skip => [:registrations]
	as :editor do
	  get 'editors/edit' => 'devise/registrations#edit', :as => 'edit_editor_registration'
	  put 'editors' => 'devise/registrations#update', :as => 'editor_registration'
	  delete 'editors' => 'devise/registrations#destroy', :as => 'destroy_editor_registration'
	end
	devise_for :admins, :skip => [:registrations]
	as :admin do
	  get 'admins/edit' => 'devise/registrations#edit', :as => 'edit_admin_registration'
	  put 'admins' => 'devise/registrations#update', :as => 'admin_registration'
	end
	match 'admin/:id' => 'admins#destroy', :via => :delete, :as => :admin_destroy_editor
	get '/admin' => 'admins#home'
	get '/admin/manage' => 'admins#manage'
	put '/admin/manage/:id' => 'admins#verify', :method => :put, :as => :verify_editor
	get '/editor' => 'editors#home'
	root 'articles#index'
	get '/search' => 'search#search'
	get '/contacts' => 'contacts#new'
	resources "contacts", only: [:new, :create]
	get '/about' => 'home#about'
end

app/views/layouts/_footer.html.erb
<div class="page_footer">
	<div class="container-fluid">
		<div class="row footer">
			<div class="col-lg-6 col-md-6 col-xs-12 footer-left">
				<p>
					<strong>Address:</strong><br>
					Editor,<br>
					Regent House,<br>
					Trinity College Dublin<br><br>
				</p>
			</div>
			<div class="col-lg-6 col-md-6 col-xs-12 footer-right">
				<p>
					Wanna write for us?<br>
					<%= link_to 'Get In Touch!', contacts_path %>
				</p>
			</div>
		</div>
	</div>
</div>

app/views/layouts/_header.html.erb
<div class="header">

	<div class="errors">
		<p class="notice"><%= notice %></p>
		<p class="alert"><%= alert %></p>
	</div>

	<div class="page_header">
		<div class="row visible-md visible-lg">
			<%= link_to root_path do %>
				<div class="col-md-5 col-lg-5 col-xs-12 piranha_title">
					<%= image_tag('PiranhaTitle.png') %>
				</div>
			<% end %>
			<div class="col-lg-7 col-mg-7">
				<div class="row">
					<div class="col-lg-12 col-md-12">
						<ul>
							<li id="search-box">
								<%= form_tag(search_path, {:class => "search-form", :method => :get}) do %>
				        			<%= text_field_tag :search, params[:search], class: "search", placeholder: "Search..." %>
								<% end %>
							</li>
						</ul>
					</div>
				</div>
				<div class="row">
					<div class="col-md-12 col-lg-12 visible-lg visible-md desktop-header">
						<ul>
							<% if admin_signed_in? %>
								<li id="log-out">
									<%= link_to destroy_admin_session_path, :method => :delete do %>
										<div class="glyphicon glyphicon-off"></div>
									<% end %>
								</li>
								<li id="admin"><%= link_to 'ADMIN', admin_path %></li>
							<% elsif editor_signed_in? %>
								<li id="log-out">
									<%= link_to destroy_editor_session_path, :method => :delete do %>
										<div class="glyphicon glyphicon-off"></div>
									<% end %>
								</li>
								<li id="admin"><%= link_to 'EDITOR', editor_path %></li>
							<% end %>
							<li><%= link_to 'CONTACT', contacts_path %></li>
							<li><%= link_to 'ABOUT US', about_path %></li>
							<li id="issues"><%= link_to 'ALL ISSUES', issue_links_path %></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
		<nav class="navbar navbar-default navbar-fixed-top collapse navbar-collapse visible-xs visible-sm">
			<div class="container">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
				</div>
				<div class="collapse navbar-collapse">
					<ul class="nav navbar-nav nav-stacked">
						<li><%= link_to 'HOME', root_path %></li>
						<li><%= link_to 'ALL ISSUES', issue_links_path %></li>
						<li><%= link_to 'ABOUT US', about_path %></li>
						<li><%= link_to 'CONTACT', contacts_path %></li>
						<% if !(admin_signed_in? || editor_signed_in?) %>
							<li><%= link_to 'EDITOR LOGIN', new_editor_session_path %></li>
							<li><%= link_to 'ADMIN LOGIN', new_admin_session_path %></li>
						<% elsif admin_signed_in? %>
							<li><%= link_to 'ADMIN', admin_path %></li>
							<li>
								<%= link_to destroy_admin_session_path, :method => :delete do %>
									<div class="glyphicon glyphicon-off"></div>
								<% end %>
							</li>
						<% elsif editor_signed_in? %>
							<li><%= link_to 'EDITOR', editor_path %></li>
							<li>
								<%= link_to destroy_editor_session_path, :method => :delete do %>
									<div class="glyphicon glyphicon-off"></div>
								<% end %>
							</li>
						<% end %>
						<li id="search-box">
							<%= form_tag(search_path, {:class => "search-form", :method => :get}) do %>
								<%= text_field_tag :search, params[:search], class: "search", placeholder: "Search..." %>
							<% end %>
						</li>
					</ul>
				</ul>
			</div>
		</nav>
	</div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ThePiranha</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width" />
</head>
<body>
<div class="page">
    <%= render "layouts/header" %>
    <div class="page-body">
    	<%= yield %>
    </div>
    <%= render "layouts/footer" %>
</div>
</body>
</html>